apiVersion: v1
kind: Service
metadata:
  name: {{ include "optix.fullname" . }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: 80
  selector:
    app: {{ include "optix.name" . }}
